from math import ceil, floor

# Define some colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
BLUE = (0, 0, 255)
BROWN = (95, 95, 0)
 
WINDOW_WIDTH = 1024
WINDOW_HEIGHT = 768

# Time since last logic update
DELTATIME = 5 # In milliseconds; 5 ms = physics update @ 200 Hz

LEVEL_WIDTH = 10
LEVEL_HEIGHT = 10

BRICK_THICKNESS = 10
BRICK_WIDTH = 0 #ceil(WINDOW_WIDTH * 0.05)
BRICK_HEIGHT = ceil(WINDOW_HEIGHT * 0.025)

WALL_THICKNESS = 6

GAMEAREA_WIDTH = 0 #ceil(WALL_THICKNESS + ((BRICK_WIDTH + BRICK_THICKNESS) * LEVEL_WIDTH))
GAMEAREA_HEIGHT = ceil(WINDOW_HEIGHT * 0.9)
GAMEAREA_X = 0 #ceil((WINDOW_WIDTH / 2.0) - (GAMEAREA_WIDTH / 2.0))
GAMEAREA_Y = ceil((WINDOW_HEIGHT - GAMEAREA_HEIGHT - (WALL_THICKNESS / 2.0)))

GAME_SPEED = 2.0
GAME_STARTINGBALLS = 3
GAME_SCOREEXTRABALL = 5000 # How many points is needed for an extra ball
 
STATE_MAINMENU = 1
STATE_GAME = 2
STATE_CHOOSEMODE = 3
STATE_PAUSE = 4
STATE_GAMEOVER = 5

ACTION_NEWGAME = 1
ACTION_QUIT = 2
ACTION_MODE1P = 3
ACTION_MODE2P = 4

GAMEOBJECT_PADDLE = 1
GAMEOBJECT_BALL = 2
GAMEOBJECT_WALL = 3
GAMEOBJECT_BRICK = 4
GAMEOBJECT_POWERUP = 5

PLAYER_ONE = 0
PLAYER_TWO = 1

DIRECTION_UP = 1
DIRECTION_DOWN = 2
DIRECTION_LEFT = 3
DIRECTION_RIGHT = 4

BALL_BOUNCESPEEDUP = 150 # How many bounces off the paddle it takes to double the speed of the ball
BALL_STARTINGSPEED = 0 #GAMEAREA_HEIGHT * 0.0075
PADDLE_STARTINGSPEED = 0 #GAMEAREA_WIDTH * 0.005

BALL_COLOR = BLUE
PADDLE_COLOR = BROWN
WALL_COLOR = RED
BRICK_COLOR = BLACK

PADDLE_THICKNESS = 1
PADDLE_WIDTH = 0 #ceil(GAMEAREA_WIDTH * 0.10)
PADDLE_HEIGHT = 0 #ceil(PADDLE_WIDTH * 0.15)

BALL_THICKNESS = 0
BALL_SIZE = 6

POWERUP_THICKNESS = 0
POWERUP_WIDTH = ceil(WINDOW_WIDTH * 0.0175)
POWERUP_HEIGHT = ceil(WINDOW_HEIGHT * 0.015)

POWERUP_DOUBLEBALL = "D"
POWERUP_DOUBLEBALL_COLOR = (127, 127, 255)
POWERUP_EXPLOSION = "E"
POWERUP_EXPLOSION_COLOR = (191, 191, 0)
POWERUP_EXPLOSION_RADIUS = 2
POWERUP_COPYBALL = "C"
POWERUP_COPYBALL_COLOR = BALL_COLOR
POWERUP_EXTRAWIDTH = "W"
POWERUP_EXTRAWIDTH_COLOR = PADDLE_COLOR

SHAPE_RECT = 1
SHAPE_CIRCLE = 2